server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebook?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.zut.edu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/mybatis-config.xml
